### ISSUE TITLE
src/wtdist.c:177: bad test 

### ISSUE THREAD

**Issue by dcb314** [osj1961/guava#24]
src/wtdist.c:177]: (warning) Logical conjunction always evaluates to false: EXPR < 1 && EXPR > 3.

Source code is

   if ( argc - optionCountPlus1 < 1 && argc - optionCountPlus1 > 3 ) {

Suggest new code

   if ( argc - optionCountPlus1 < 1 || argc - optionCountPlus1 > 3 ) {

**Comment by osj1961** [comment]
Fixed with commit 45698f22985dec282f953dbb5bae85c4068e0981
Thanks!
