### ISSUE TITLE
Randomization related test failures

### ISSUE THREAD

**Issue by osj1961** [osj1961/guava#6]
some of the tests in guava.tst use randomized inputs.  The expected outputs can't necessarily be compared to previous results.

**Comment by osj1961** [comment]
The way to deal w/ this issue is to compute the same thing in 2 different ways based on the random item and then compare them.  The expected output becomes "true" rather than something that has to do w/ the randomized object.

**Comment by alex-konovalov** [comment]
You can also use `;;` to suppress output and then check that some properties/attributes of the output are correct.

**Comment by osj1961** [comment]
Done.
